# Generated by Django 6.0.7 on 2026-07-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='media/profil.png', upload_to='profil_pic/'),
        ),
    ]
