# Generated by Django 6.0.7 on 2026-07-25 21:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_image_postmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmedia',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
