# Generated by Django 6.0.7 on 2026-07-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postmedia_created_at_postmedia_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
    ]
