# Generated by Django 6.0.7 on 2026-07-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postmedia_is_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
