# Generated by Django 6.0.7 on 2026-08-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_created_at_post_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('dasturlash', 'dasturlash'), ('xabarlar', 'xabarlar'), ('talim', 'talim'), ('moliya', 'moliya'), ('tibbiyot', 'tibbiyot')], default='xabarlar', max_length=200),
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
